# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('title', models.CharField(max_length=128, unique=True)),
                ('company', models.CharField(max_length=128)),
            ],
        ),
    ]
